In [1]:
import random
import glob, os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# import seaborn as sns
pd.options.mode.chained_assignment = None # to remove some warnings

In [2]:
def get_current_year():
    from datetime import datetime
    today = datetime.today()
    datem = datetime(today.year, today.month, 1)
    return datem.year

def get_weekly_data(week, year):
    """ get player data for designated week """
    file_path = f"./csv's/{year}/year-{year}-week-{week}-DK-player_data.csv"
    df = pd.read_csv(file_path)
    return df

def get_ytd_season_data(year, current_week):
    """ get data for current season up to most recent week """
    df = get_weekly_data(1,year)
    for week in range(2,current_week+1):
        try:
            df = df.append(get_weekly_data(week, year), ignore_index=True)
        except:
            print("No data for week: "+str(week))
    df = df.drop(['Unnamed: 0', 'Year'], axis=1)
    return df

def get_season_data(year, drop_year=True):
    """ get entire season of data """
    df = get_weekly_data(1,year)
    for week in range(2,17):
        try:
            df = df.append(get_weekly_data(week, year), ignore_index=True)
        except:
            print("No data for week: "+str(week))
    if drop_year:
        df = df.drop(['Unnamed: 0', 'Year'], axis=1)
    else:
        df = df.drop(['Unnamed: 0'], axis=1)
    return df

def check_dk_data():
    list_of_files = glob.glob("./csv's/dkdata/*.csv") 
    sorted_files = sorted(list_of_files, key=os.path.getctime)
    most_recent_dkdata = sorted_files[-1] 
    df = pd.read_csv("./csv's/dkdata/fixed*.csv")

In [3]:
year = get_current_year()
week = 7
pred_file_path = f"./csv's/dkdata/predictions/dk_preds-week-{week}.csv"
res_file_path = f"./csv's/{year}/year-{year}-week-{week}-DK-player_data.csv"
pred_df = pd.read_csv(pred_file_path).drop(columns='Unnamed: 0')
res_df = pd.read_csv(res_file_path).drop(columns='Unnamed: 0')

In [4]:
res_df['pts/1k'] = res_df['DK points'] / res_df['DK salary'] * 1000
pred_sort = 'pred'
res_sort = 'pts/1k'

In [5]:
# QB's Predictions
filt=(pred_df.Pos == 'QB')&(pred_df.pred>12)
pred_df.loc[filt].sort_values(by=pred_sort, ascending=False)

,Pos,Name,Salary,Team,h/a,Oppt,Oppt_pts_allowed_lw,pred
40,QB,"Dallas, DeeJay",5000.0,chi,a,tam,64.10,18.203289
58,QB,"Love, Jordan",4200.0,gnb,h,was,138.48,17.242961
6,QB,"Rodgers, Aaron",7500.0,gnb,h,was,138.48,17.102716
4,QB,"Mahomes II, Patrick",8400.0,kan,a,ten,129.62,17.016151
28,QB,"Fields, Justin",5300.0,chi,a,tam,64.10,16.163273
81,QB,"Eason, Jacob",4000.0,ind,a,sfo,87.86,15.634343
17,QB,"Carr, Derek",6000.0,lvr,h,phi,120.78,15.607813
26,QB,"Wentz, Carson",5400.0,ind,a,sfo,87.86,15.607813
19,QB,"Winston, Jameis",5900.0,nor,a,sea,95.96,15.547082
41,QB,"Hill, Taysom",5000.0,nor,a,sea,95.96,15.547082
77,QB,"Peterman, Nathan",4000.0,lvr,h,phi,120.78,14.923390
29,QB,"Jones, Mac",5300.0,nwe,h,nyj,126.68,14.801786
18,QB,"Darnold, Sam",5900.0,car,a,nyg,133.24,14.395306
67,QB,"Walker, P.J.",4000.0,car,a,nyg,133.24,13.400250
37,QB,"Wilson, Zach",5100.0,nyj,a,nwe,157.50,12.135905

In [6]:
# QB's Results
filt=(res_df.Pos == 'QB')&(res_df['DK points']>12)
res_df.loc[filt].sort_values(by=res_sort, ascending=False)

,Week,Year,Name,Pos,Team,h/a,Oppt,DK points,DK salary,pts/1k
2,7,2021,"Tagovailoa, Tua",QB,mia,h,atl,28.54,5500,5.189091
0,7,2021,"Burrow, Joe",QB,cin,a,bal,30.64,6200,4.941935
3,7,2021,"Jones, Mac",QB,nwe,h,nyj,25.18,5300,4.750943
11,7,2021,"Heinicke, Taylor",QB,was,a,gnb,22.22,5200,4.273077
1,7,2021,"Stafford, Matthew",QB,lar,h,det,30.16,7100,4.247887
12,7,2021,"Wentz, Carson",QB,ind,a,sfo,21.30,5400,3.944444
10,7,2021,"Ryan, Matt",QB,atl,a,mia,22.44,5700,3.936842
8,7,2021,"Carr, Derek",QB,lvr,h,phi,23.02,6000,3.836667
5,7,2021,"Hurts, Jalen",QB,phi,a,oak,24.54,6900,3.556522
4,7,2021,"Rodgers, Aaron",QB,gnb,h,was,24.66,7500,3.288000
14,7,2021,"Jones, Daniel",QB,nyg,h,car,17.52,5400,3.244444
13,7,2021,"Tannehill, Ryan",QB,ten,h,kan,20.40,6400,3.187500
6,7,2021,"Brady, Tom",QB,tam,h,chi,24.44,7700,3.174026
7,7,2021,"Jackson, Lamar",QB,bal,h,cin,23.08,7400,3.118919
15,7,2021,"Winston, Jameis",QB,nor,a,sea,16.88,5900,2.861017
9,7,2021,"Murray, Kyler",QB,ari,h,hou,22.44,8500,2.640000
16,7,2021,"Bridgewater, Teddy",QB,den,a,cle,14.78,5600,2.639286
17,7,2021,"Goff, Jared",QB,det,a,lar,13.02,5000,2.604000
18,7,2021,"Keenum, Case",QB,cle,h,den,12.66,5000,2.532000

In [7]:
# RB's Predictions
filt=(pred_df.Pos == 'RB')&(pred_df.pred>12)
pred_df.loc[filt].sort_values(by=pred_sort, ascending=False)

,Pos,Name,Salary,Team,h/a,Oppt,Oppt_pts_allowed_lw,pred
74,RB,"Burton, Michael",4000.0,kan,a,ten,129.62,19.871473
75,RB,"Hill, Kylin",4000.0,gnb,h,was,138.48,17.308147
88,RB,"Armah, Alex",4000.0,nor,a,sea,95.96,17.268797
51,RB,"Dillon, AJ",4600.0,gnb,h,was,138.48,17.226581
62,RB,"McKinnon, Jerick",4100.0,kan,a,ten,129.62,17.226581
7,RB,"Jones, Aaron",7500.0,gnb,h,was,138.48,17.129528
24,RB,"Edwards-Helaire, Clyde",5400.0,kan,a,ten,129.62,17.077647
20,RB,"Williams, Darrel",5800.0,kan,a,ten,129.62,17.077318
65,RB,"Nall, Ryan",4000.0,chi,a,tam,64.10,16.739394
66,RB,"Pierce, Artavis",4000.0,chi,a,tam,64.10,16.739394
32,RB,"Herbert, Khalil",5200.0,chi,a,tam,64.10,16.556555
22,RB,"Williams, Damien",5500.0,chi,a,tam,64.10,16.163273
35,RB,"Montgomery, David",5100.0,chi,a,tam,64.10,16.163273
83,RB,"Wilkins, Jordan",4000.0,ind,a,sfo,87.86,15.725587
82,RB,"Mack, Marlon",4000.0,ind,a,sfo,87.86,15.725587
60,RB,"Hines, Nyheim",4200.0,ind,a,sfo,87.86,15.725587
9,RB,"Taylor, Jonathan",7100.0,ind,a,sfo,87.86,15.661364
87,RB,"Washington, Dwayne",4000.0,nor,a,sea,95.96,15.634343
86,RB,"Ozigbo, Devine",4000.0,nor,a,sea,95.96,15.634343
1,RB,"Kamara, Alvin",8900.0,nor,a,sea,95.96,15.607813
78,RB,"Barber, Peyton",4000.0,lvr,h,phi,120.78,15.547082
70,RB,"Bolden, Brandon",4000.0,nwe,h,nyj,126.68,15.153731
80,RB,"Ingold, Alec",4000.0,lvr,h,phi,120.78,14.841585
79,RB,"Richard, Jalen",4000.0,lvr,h,phi,120.78,14.841585
14,RB,"Jacobs, Josh",6200.0,lvr,h,phi,120.78,14.801786
43,RB,"Drake, Kenyan",4900.0,lvr,h,phi,120.78,14.801786
71,RB,"Taylor, J.J.",4000.0,nwe,h,nyj,126.68,14.664830
72,RB,"White, James",4000.0,nwe,h,nyj,126.68,14.664830
73,RB,"Johnson, Jakob",4000.0,nwe,h,nyj,126.68,14.664830
48,RB,"Stevenson, Rhamondre",4700.0,nwe,h,nyj,126.68,14.637158
21,RB,"Harris, Damien",5700.0,nwe,h,nyj,126.68,14.637158
68,RB,"Freeman, Royce",4000.0,car,a,nyg,133.24,13.344444
3,RB,"McCaffrey, Christian",8500.0,car,a,nyg,133.24,13.344444
16,RB,"Hubbard, Chuba",6100.0,car,a,nyg,133.24,13.101724
69,RB,"Coleman, Tevin",4000.0,nyj,a,nwe,157.50,12.071858
46,RB,"Carter, Michael",4800.0,nyj,a,nwe,157.50,12.071858
53,RB,"Johnson, Ty",4300.0,nyj,a,nwe,157.50,12.071511

In [8]:
# RB's Results
filt=(res_df.Pos == 'RB')&(res_df['DK points']>12)
res_df.loc[filt].sort_values(by=res_sort, ascending=False)

,Week,Year,Name,Pos,Team,h/a,Oppt,DK points,DK salary,pts/1k
39,7,2021,"Johnson, D'Ernest",RB,cle,h,den,27.8,4800,5.791667
42,7,2021,"Bolden, Brandon",RB,nwe,h,nyj,19.9,4000,4.975000
38,7,2021,"Harris, Damien",RB,nwe,h,nyj,28.3,5700,4.964912
37,7,2021,"Swift, D'Andre",RB,det,a,lar,28.4,6000,4.733333
36,7,2021,"Kamara, Alvin",RB,nor,a,sea,36.9,8900,4.146067
41,7,2021,"Herbert, Khalil",RB,chi,a,tam,21.3,5200,4.096154
51,7,2021,"Taylor, J.J.",RB,nwe,h,nyj,15.6,4000,3.900000
43,7,2021,"Mitchell, Elijah",RB,sfo,h,ind,19.7,5100,3.862745
45,7,2021,"Carter, Michael",RB,nyj,a,nwe,17.4,4800,3.625000
52,7,2021,"Gainwell, Kenny",RB,phi,a,oak,15.1,4200,3.595238
48,7,2021,"Drake, Kenyan",RB,lvr,h,phi,16.9,4900,3.448980
46,7,2021,"Williams, Javonte",RB,den,a,cle,17.2,5100,3.372549
44,7,2021,"Gaskin, Myles",RB,mia,h,atl,17.7,5300,3.339623
40,7,2021,"Taylor, Jonathan",RB,ind,a,sfo,22.0,7100,3.098592
54,7,2021,"Perine, Samaje",RB,cin,a,bal,14.5,4700,3.085106
56,7,2021,"Johnson, Ty",RB,nyj,a,nwe,13.1,4300,3.046512
57,7,2021,"Freeman, Devonta",RB,bal,h,cin,12.9,4400,2.931818
47,7,2021,"Fournette, Leonard",RB,tam,h,chi,17.0,6400,2.656250
53,7,2021,"Booker, Devontae",RB,nyg,h,car,14.6,5500,2.654545
50,7,2021,"Jacobs, Josh",RB,lvr,h,phi,15.8,6200,2.548387
55,7,2021,"Patterson, Cordarrelle",RB,atl,a,mia,14.1,6300,2.238095
58,7,2021,"Conner, James",RB,ari,h,hou,12.4,5600,2.214286
49,7,2021,"Henry, Derrick",RB,ten,h,kan,16.4,9200,1.782609

In [9]:
# WR's Predictions
filt=(pred_df.Pos == 'WR')&(pred_df.pred>12)
pred_df.loc[filt].sort_values(by=pred_sort, ascending=False)

,Pos,Name,Salary,Team,h/a,Oppt,Oppt_pts_allowed_lw,pred
76,WR,"Cobb, Randall",4000.0,gnb,h,was,138.48,20.721538
0,WR,"Adams, Davante",8900.0,gnb,h,was,138.48,20.194574
108,WR,"Byrd, Damiere",3000.0,chi,a,tam,64.10,18.524103
106,WR,"Mickens, Jaydon",3000.0,NaN,h,NaN,0.00,18.377083
96,WR,"Campbell, Parris",3500.0,ind,a,sfo,87.86,17.323228
124,WR,"Taylor, Malik",3000.0,gnb,h,was,138.48,17.244186
123,WR,"St. Brown, Equanimeous",3000.0,gnb,h,was,138.48,17.244186
122,WR,"Rodgers, Amari",3000.0,gnb,h,was,138.48,17.244186
89,WR,"Valdes-Scantling, Marquez",3900.0,gnb,h,was,138.48,17.244186
59,WR,"Lazard, Allen",4200.0,gnb,h,was,138.48,17.244186
54,WR,"Hardman, Mecole",4300.0,kan,a,ten,129.62,17.242961
101,WR,"Gordon, Josh",3200.0,kan,a,ten,129.62,17.242961
97,WR,"Robinson, Demarcus",3400.0,kan,a,ten,129.62,17.226581
121,WR,"Kemp, Marcus",3000.0,kan,a,ten,129.62,17.226581
34,WR,"Callaway, Marquez",5200.0,nor,a,sea,95.96,17.226581
99,WR,"Pringle, Byron",3300.0,kan,a,ten,129.62,17.226581
2,WR,"Hill, Tyreek",8600.0,kan,a,ten,129.62,17.102716
109,WR,"Grant, Jakeem",3000.0,chi,a,tam,64.10,16.739394
107,WR,"Goodwin, Marquise",3000.0,chi,a,tam,64.10,16.739394
110,WR,"Webster, Nsimba",3000.0,chi,a,tam,64.10,16.649600
36,WR,"Robinson, Allen",5100.0,chi,a,tam,64.10,16.163273
50,WR,"Mooney, Darnell",4600.0,chi,a,tam,64.10,16.163273
131,WR,"Harris, De'Michael",3000.0,ind,a,sfo,87.86,15.750876
130,WR,"Strachan, Mike",3000.0,ind,a,sfo,87.86,15.750876
129,WR,"Dulin, Ashton",3000.0,ind,a,sfo,87.86,15.750876
55,WR,"Pascal, Zach",4300.0,ind,a,sfo,87.86,15.750876
44,WR,"Hilton, T.Y.",4900.0,ind,a,sfo,87.86,15.725587
38,WR,"Pittman Jr., Michael",5100.0,ind,a,sfo,87.86,15.725587
57,WR,"Harris, Deonte",4300.0,nor,a,sea,95.96,15.661364
135,WR,"Hogan, Chris",3000.0,nor,a,sea,95.96,15.661364
134,WR,"Montgomery, Ty",3000.0,nor,a,sea,95.96,15.661364
136,WR,"Humphrey, Lil'Jordan",3000.0,nor,a,sea,95.96,15.661364
105,WR,"Stills, Kenny",3100.0,nor,a,sea,95.96,15.661364
92,WR,"Agholor, Nelson",3700.0,nwe,h,nyj,126.68,15.169635
52,WR,"Bourne, Kendrick",4400.0,nwe,h,nyj,126.68,15.169635
128,WR,"Snead, Willie",3000.0,lvr,h,phi,120.78,14.841585
127,WR,"Jones, Zay",3000.0,lvr,h,phi,120.78,14.841585
64,WR,"Edwards, Bryan",4100.0,lvr,h,phi,120.78,14.841585
23,WR,"Ruggs III, Henry",5500.0,lvr,h,phi,120.78,14.801786
47,WR,"Renfrow, Hunter",4800.0,lvr,h,phi,120.78,14.801786
120,WR,"Slater, Matthew",3000.0,nwe,h,nyj,126.68,14.664830
118,WR,"Harry, N'Keal",3000.0,nwe,h,nyj,126.68,14.664830
119,WR,"Olszewski, Gunner",3000.0,nwe,h,nyj,126.68,14.664830
30,WR,"Meyers, Jakobi",5300.0,nwe,h,nyj,126.68,14.637158
45,WR,"Anderson, Robby",4800.0,car,a,nyg,133.24,14.126143
100,WR,"Marshall, Terrace",3200.0,car,a,nyg,133.24,13.344444
8,WR,"Moore, D.J.",7100.0,car,a,nyg,133.24,13.344444
114,WR,"Smith, Shi",3000.0,car,a,nyg,133.24,13.344444
113,WR,"Erickson, Alex",3000.0,car,a,nyg,133.24,13.344444
112,WR,"Zylstra, Brandon",3000.0,car,a,nyg,133.24,13.344444
42,WR,"Crowder, Jamison",4900.0,nyj,a,nwe,157.50,12.071858
115,WR,"Berrios, Braxton",3000.0,nyj,a,nwe,157.50,12.071858
94,WR,"Moore, Elijah",3600.0,nyj,a,nwe,157.50,12.071511
117,WR,"Smith, Jeff",3000.0,nyj,a,nwe,157.50,12.071511
116,WR,"Mims, Denzel",3000.0,nyj,a,nwe,157.50,12.071511

In [10]:
# WR's Results
filt=(res_df.Pos == 'WR')&(res_df['DK points']>12)
res_df.loc[filt].sort_values(by=res_sort, ascending=False)

,Week,Year,Name,Pos,Team,h/a,Oppt,DK points,DK salary,pts/1k
128,7,2021,"Chase, Ja'Marr",WR,cin,a,bal,37.10,6200,5.983871
143,7,2021,"Pettis, Dante",WR,nyg,h,car,15.54,3000,5.180000
129,7,2021,"Evans, Mike",WR,tam,h,chi,31.60,6500,4.861538
127,7,2021,"Kupp, Cooper",WR,lar,h,det,40.60,8400,4.833333
130,7,2021,"Brown, A.J.",WR,ten,h,kan,30.30,6300,4.809524
132,7,2021,"Godwin, Chris",WR,tam,h,chi,28.10,5900,4.762712
134,7,2021,"Pittman Jr., Michael",WR,ind,a,sfo,23.50,5100,4.607843
135,7,2021,"Raymond, Kalif",WR,det,a,lar,20.60,4700,4.382979
141,7,2021,"Gage, Russell",WR,atl,a,mia,16.70,4000,4.175000
131,7,2021,"McLaurin, Terry",WR,was,a,gnb,28.20,6900,4.086957
148,7,2021,"Jefferson, Van",WR,lar,h,det,14.30,3500,4.085714
140,7,2021,"Lazard, Allen",WR,gnb,h,was,17.00,4200,4.047619
156,7,2021,"Pringle, Byron",WR,kan,a,ten,12.30,3300,3.727273
142,7,2021,"Bourne, Kendrick",WR,nwe,h,nyj,15.80,4400,3.590909
152,7,2021,"Agholor, Nelson",WR,nwe,h,nyj,13.10,3700,3.540541
133,7,2021,"Samuel, Deebo",WR,sfo,h,ind,25.00,7300,3.424658
137,7,2021,"Brown, Marquise",WR,bal,h,cin,19.00,5800,3.275862
149,7,2021,"Edwards, Bryan",WR,lvr,h,phi,13.30,4100,3.243902
145,7,2021,"Kirk, Christian",WR,ari,h,hou,15.00,5300,2.830189
147,7,2021,"Davis, Corey",WR,nyj,a,nwe,14.70,5200,2.826923
144,7,2021,"Waddle, Jaylen",WR,mia,h,atl,15.30,5600,2.732143
151,7,2021,"Higgins, Tee",WR,cin,a,bal,13.20,4900,2.693878
153,7,2021,"Renfrow, Hunter",WR,lvr,h,phi,12.80,4800,2.666667
139,7,2021,"Metcalf, D.K.",WR,sea,h,nor,17.60,6800,2.588235
138,7,2021,"Hopkins, DeAndre",WR,ari,h,hou,18.30,7700,2.376623
146,7,2021,"Woods, Robert",WR,lar,h,det,15.00,6400,2.343750
136,7,2021,"Adams, Davante",WR,gnb,h,was,19.60,8900,2.202247
155,7,2021,"Ridley, Calvin",WR,atl,a,mia,12.60,6600,1.909091
150,7,2021,"Moore, D.J.",WR,car,a,nyg,13.30,7100,1.873239
154,7,2021,"Hill, Tyreek",WR,kan,a,ten,12.70,8600,1.476744

In [11]:
# TE's Predictions
filt=(pred_df.Pos == 'TE')&(pred_df.pred>12)
pred_df.loc[filt].sort_values(by=pred_sort, ascending=False)

,Pos,Name,Salary,Team,h/a,Oppt,Oppt_pts_allowed_lw,pred
159,TE,"Dafney, Dominique",2500.0,gnb,h,was,138.48,20.813768
152,TE,"Bell, Blake",2500.0,kan,a,ten,129.62,19.871473
157,TE,"Deguara, Josiah",2500.0,gnb,h,was,138.48,17.308147
104,TE,"Alie-Cox, Mo",3100.0,ind,a,sfo,87.86,17.308147
158,TE,"Davis, Tyler",2500.0,gnb,h,was,138.48,17.308147
156,TE,"Lewis, Marcedes",2500.0,gnb,h,was,138.48,17.244186
95,TE,"Tonyan, Robert",3500.0,gnb,h,was,138.48,17.244186
154,TE,"Fortson, Jody",2500.0,kan,a,ten,129.62,17.242961
153,TE,"Gray, Noah",2500.0,kan,a,ten,129.62,17.242961
155,TE,"Winchester, James",2500.0,kan,a,ten,129.62,17.129528
5,TE,"Kelce, Travis",7600.0,kan,a,ten,129.62,17.077318
144,TE,"Graham, Jimmy",2500.0,chi,a,tam,64.10,16.739394
146,TE,"Holtz, J.P.",2500.0,chi,a,tam,64.10,16.739394
147,TE,"Horsted, Jesper",2500.0,chi,a,tam,64.10,16.739394
111,TE,"Kmet, Cole",3000.0,chi,a,tam,64.10,16.649600
145,TE,"James, Jesse",2500.0,chi,a,tam,64.10,16.649600
143,TE,"Doyle, Jack",2700.0,ind,a,sfo,87.86,15.725587
162,TE,"Granson, Kylen",2500.0,ind,a,sfo,87.86,15.725587
164,TE,"Griffin, Garrett",2500.0,nor,a,sea,95.96,15.634343
137,TE,"Trautman, Adam",3000.0,nor,a,sea,95.96,15.634343
103,TE,"Johnson, Juwan",3200.0,nor,a,sea,95.96,15.634343
161,TE,"Carrier, Derek",2500.0,lvr,h,phi,120.78,15.547082
11,TE,"Waller, Darren",6700.0,lvr,h,phi,120.78,14.841585
160,TE,"Moreau, Foster",2500.0,lvr,h,phi,120.78,14.841585
140,TE,"Smith, Jonnu",2800.0,nwe,h,nyj,126.68,14.664830
61,TE,"Henry, Hunter",4100.0,nwe,h,nyj,126.68,14.664830
142,TE,"Tremble, Tommy",2700.0,car,a,nyg,133.24,13.344444
139,TE,"Thomas, Ian",2900.0,car,a,nyg,133.24,13.344444
148,TE,"Thompson, Colin",2500.0,car,a,nyg,133.24,13.344444
151,TE,"Brown, Daniel",2500.0,nyj,a,nwe,157.50,12.071858
150,TE,"Wesco, Trevon",2500.0,nyj,a,nwe,157.50,12.071511
149,TE,"Kroft, Tyler",2500.0,nyj,a,nwe,157.50,12.071511

In [12]:
# TE's Results
filt=(res_df.Pos == 'TE')&(res_df['DK points']>12)
res_df.loc[filt].sort_values(by=res_sort, ascending=False)

,Week,Year,Name,Pos,Team,h/a,Oppt,DK points,DK salary,pts/1k
263,7,2021,"Uzomah, C.J.",TE,cin,a,bal,24.1,3000,8.033333
265,7,2021,"Moreau, Foster",TE,lvr,h,phi,18.0,2500,7.200000
266,7,2021,"Tonyan, Robert",TE,gnb,h,was,16.3,3500,4.657143
264,7,2021,"Gesicki, Mike",TE,mia,h,atl,21.5,4700,4.574468
262,7,2021,"Pitts, Kyle",TE,atl,a,mia,26.3,5900,4.457627
267,7,2021,"Ertz, Zach",TE,ari,h,hou,16.0,3900,4.102564
268,7,2021,"Kelce, Travis",TE,kan,a,ten,13.5,7600,1.776316

In [13]:
# Def's Results
filt=(res_df.Pos == 'Def')&(res_df['DK points']>5)
res_df.loc[filt].sort_values(by=res_sort, ascending=False)

,Week,Year,Name,Pos,Team,h/a,Oppt,DK points,DK salary,pts/1k
336,7,2021,Tennessee,Def,ten,h,kan,17.0,2100,8.095238
335,7,2021,New York G,Def,nyg,h,car,17.0,2500,6.800000
334,7,2021,Tampa Bay,Def,tam,h,chi,21.0,4000,5.250000
337,7,2021,Green Bay,Def,gnb,h,was,14.0,3300,4.242424
340,7,2021,Indianapolis,Def,ind,a,sfo,11.0,3000,3.666667
339,7,2021,Arizona,Def,ari,h,hou,11.0,3100,3.548387
338,7,2021,New England,Def,nwe,h,nyj,12.0,3400,3.529412
343,7,2021,Houston,Def,hou,a,ari,7.0,2000,3.500000
345,7,2021,Washington,Def,was,a,gnb,7.0,2200,3.181818
342,7,2021,Seattle,Def,sea,h,nor,8.0,2900,2.758621
341,7,2021,New Orleans,Def,nor,a,sea,9.0,3400,2.647059
348,7,2021,Atlanta,Def,atl,a,mia,6.0,2700,2.222222
347,7,2021,Cincinnati,Def,cin,a,bal,6.0,2800,2.142857
346,7,2021,Las Vegas,Def,lvr,h,phi,6.0,3000,2.000000
344,7,2021,LA Rams,Def,lar,h,det,7.0,5000,1.400000

In [14]:
big_df_columns = ['Year', 'Week', 'Name', 'Pos', 'Team', 'h/a', 'Oppt', 'DK points', 'DK salary']
big_df = pd.DataFrame(columns=big_df_columns)
for num in range(2014,get_current_year()+1):
    big_df = big_df.append(get_season_data(num, drop_year=False))
big_df['pts/1k'] = big_df['DK points'] / big_df['DK salary'] * 1000

No data for week: 8
No data for week: 9
No data for week: 10
No data for week: 11
No data for week: 12
No data for week: 13
No data for week: 14
No data for week: 15
No data for week: 16

In [15]:
team = 'Buffalo'
big_df.loc[big_df.Name == player_name].sort_values(by=res_sort, ascending=False)

NameError: name 'player_name' is not defined